# Athens Diachronic Corpus - ELIDEK Project
title: Athens Diachronic Corpus
email: your-email@university.gr
description: >-
  ΕΛΙΔΕΚ/ELIDEK funded project for diachronic linguistic analysis
  of Greek texts through computational methods.
baseurl: "/AthensDiaCorpus"
url: "https://nlavidas.github.io"

# Build settings
remote_theme: alshedivat/al-folio
plugins:
  - jekyll-remote-theme
  - jekyll-paginate-v2
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed

# Basic settings
footer_text: >
  Funded by ΕΛΙΔΕΚ/ELIDEK. Athens Diachronic Corpus Project 2024-2027.

# Collections
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

# Display settings
enable_google_analytics: false
enable_panelbear_analytics: false
enable_google_verification: false

# Blog
blog_name: Project News
blog_nav_title: News
blog_description: Updates from the Athens Diachronic Corpus project
